server:
  compression:
    enabled: true
spring:
  config:
    import: classpath:config/application-mysql.yml
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: update
hoode:
  jwt:
    secret: your-secret
    expiration-time: 360H